apiVersion: v1
kind: Service
metadata:
  name: sargam-web-service
spec:
  selector:
    app: sargam-api
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sargam-web
spec:
  selector:
    matchLabels:
      app: sargam-web
  replicas: 4
  template:
    metadata:
      labels:
        app: sargam-web
    spec:
      containers:
      - name: sargam-web
        image: sargam-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
